import {species,scenarios,create,step,toggle,viable,plantTotal} from './model.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let page=0,key='healthy',habitat=create(),log=[],prediction='skip',observed='',done=new Set(),timer=null;
const button=(id,text,primary=false)=>`<button id="${id}" class="${primary?'primary':''}">${text}</button>`;
function stop(){if(timer){clearInterval(timer);timer=null;}}
function reset(){stop();habitat=create(key);log=[];prediction='skip';observed='';render();}
function go(p){stop();page=p;key=p===3?'repair':p===4?'final':'healthy';reset();$('#main').focus();}
function icon(id){const leaf='<path d="M15 45C3 15 30 3 49 9c1 28-15 43-34 36Z" fill="#235744"/><path d="m15 44 23-23" stroke="#f7f3e8" stroke-width="3"/>';return `<svg viewBox="0 0 60 60" width="54" height="54" aria-hidden="true">${id==='grass'?'<path d="M29 54Q0 26 7 8q24 15 22 46M30 54Q56 25 48 6 29 23 30 54M30 54V7" fill="#235744" stroke="#235744" stroke-width="3"/>':id==='clover'?leaf:id==='rabbit'?'<ellipse cx="22" cy="16" rx="5" ry="13" fill="#9a653c"/><ellipse cx="37" cy="15" rx="5" ry="13" fill="#9a653c"/><ellipse cx="30" cy="40" rx="20" ry="16" fill="#9a653c"/><circle cx="23" cy="36" r="2"/><circle cx="38" cy="36" r="2"/>':id==='fox'?'<path d="M6 9 23 18h14L54 9l-5 32-19 15L11 41Z" fill="#b64b28"/><path d="m13 33 17 19 17-19-17 10Z" fill="#fffdf7"/><circle cx="20" cy="29" r="2"/><circle cx="40" cy="29" r="2"/>':'<ellipse cx="30" cy="37" rx="23" ry="17" fill="#726b53"/><circle cx="15" cy="21" r="8" fill="#726b53"/><circle cx="24" cy="35" r="2"/><circle cx="43" cy="35" r="2"/>'}</svg>`;}
function top(label,title,text){return `<p class="eyebrow">${label}</p><h1>${title}</h1><p class="intro">${text}</p>`;}
function defs(){return '<details><summary>Words to explore</summary><p><strong>Producer:</strong> a plant makes food using light, water and carbon dioxide. <strong>Herbivore:</strong> an animal that eats plants. <strong>Predator:</strong> an animal that eats other animals.</p><p><strong>Support:</strong> our made-up 0–10 indicator of how well this habitat can support a species. It is not a population count or a scientific measurement.</p></details>';}
function web(){return `<section class="card"><h3>Follow the food</h3><p class="mini">Every arrow below means “food → consumer”: energy is passed from the food to the animal eating it.</p><div class="support">Grass → rabbit → fox<br>Clover → rabbit → fox<br>Grass → field vole → fox</div><p>Light supplies energy for plant growth. Water is a resource plants need. Foxes get food from animals, not directly from sunlight.</p></section>`;}
function home(){return `${top('WELCOME TO MEADOW LAB','A meadow is a team.','Plants need resources. Animals need food. Try changing one thing and follow what happens.')}<section class="card"><div class="picture">${species.map(s=>icon(s.id)).join('')}</div><h3>First, a healthy example</h3><p>With water 6 and light 6, both plants can grow. Grass and clover support rabbits; grass supports field voles. Rabbits and voles can feed foxes.</p><p>Our support scores start at 6. One step takes each to 7 because its needs were met. A real meadow is much more complex.</p>${button('start','Explore the meadow →',true)}</section>${web()}${defs()}`;}
function select(id,label,values,value){return `<label for="${id}">${label}<select id="${id}">${values.map(v=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${v}</option>`).join('')}</select></label>`;}
function display(){return `<div class="row"><h3>Step ${habitat.tick} · ${scenarios[key].name}</h3><span>${timer?'Running slowly':'Paused'}</span></div><p class="mini">Illustrative support scores: 0–10. Not counts of animals. Zero means no current support, not a depiction of death.</p><div class="organisms">${species.map(s=>{const o=habitat.organisms[s.id];return `<article class="organism">${icon(s.id)}<h3>${s.name}</h3><p>${s.role}</p><label for="meter-${s.id}">Support ${o.level}/10 ${o.present?'':'· not included'}</label><meter id="meter-${s.id}" min="0" max="10" value="${o.level}">${o.level} of 10</meter><button data-organism="${s.id}" aria-pressed="${o.present}">${o.present?'Remove':'Add'} ${s.name}</button></article>`;}).join('')}</div>`;}
function panel(){return `<section class="card"><div class="controls">${select('water','Water (model units)',[0,1,2,3,4,5,6,7,8,9,10],habitat.water)}${select('light','Light (model units)',[0,1,2,3,4,5,6,7,8,9,10],habitat.light)}</div><p class="mini">Controls describe conditions for the next step. Changing them does not instantly heal the habitat. Species additions begin at support 4.</p><div class="controls"><label for="prediction">Predict plant support on the next step<select id="prediction"><option value="skip" ${prediction==='skip'?'selected':''}>Skip for now</option><option value="up" ${prediction==='up'?'selected':''}>It will rise</option><option value="down" ${prediction==='down'?'selected':''}>It will fall</option><option value="same" ${prediction==='same'?'selected':''}>It will stay the same</option></select></label></div><div id="habitat">${display()}</div><div class="controls">${button('step','Advance one step',true)}${button('play',timer?'Pause':'Run slowly')}${button('reset','Reset scenario')}</div><p class="feedback" id="comparison" role="status">${observed||'Make a prediction, or skip it. Then advance one step.'}</p><div id="log">${logView()}</div></section>`;}
function logView(){return !log.length?'<p class="mini">The step journal will explain each change.</p>':`<h3>Step ${habitat.tick} journal</h3><div class="table-scroll" tabindex="0" role="region" aria-label="Inspect changes"><table><thead><tr><th>Organism</th><th>Before → after</th><th>Why?</th></tr></thead><tbody>${log.map(r=>`<tr><td>${r.name}</td><td>${r.before} → ${r.after}</td><td>${r.reason}</td></tr>`).join('')}</tbody></table></div>`;}
function checks(question,answers,hint){return `<section class="card"><h3>${question}</h3><div class="choices">${answers.map(([v,t])=>`<label><input type="radio" name="answer" value="${v}">${t}</label>`).join('')}</div><details><summary>A little help</summary><p>${hint}</p></details>${button('check','Check my habitat & idea',true)}<p class="feedback" id="feedback" role="status"></p></section>`;}
function build(){return `${top('1 / BUILD','Who belongs together?','Try removing a food source. Watch one step. Then build a supported meadow with both plants, both herbivores and the fox.')}${panel()}${web()}${checks('Which link belongs in this meadow?', [['food','Grass → field vole → fox'],['sun','Sunlight → fox → grass']],'Look for a plant first, then an animal that eats it. Use the food map. Add back missing species and give enough light and water.')}${next(2)}`;}
function experiment(){return `${top('2 / PREDICT & EXPERIMENT','One change can travel.','Choose a starting scene. Predict what the plants will do. Step through and look for later changes in animal support.')}<div class="controls"><label for="scenario">Starting scenario<select id="scenario">${['healthy','dry','shade'].map(k=>`<option value="${k}" ${k===key?'selected':''}>${scenarios[k].name}</option>`).join('')}</select></label></div>${panel()}${checks('What could a dry spell change first?', [['plants','Plant growth can fall; later there may be less food support for animals.'],['fox','Foxes get less sunlight to eat.']],'Check the plant rows first. Animals use the food support at the beginning of a step, so effects can take time.')}${next(3)}`;}
function restore(){return `${top('3 / RESTORE','Something is missing.','The meadow has clover but no grass. A field vole needs grass in this model. Diagnose the food link, make a repair, then step until the habitat has support again.')}${panel()}${web()}${checks('Which repair supplies the missing food link?', [['grass','Add grass, keep enough water and light, then watch the next steps.'],['fox','Add more foxes; they make grass for the vole.']],'Restore the food source before expecting its consumer to recover. Scores only change through model steps.')}${next(4)}`;}
function final(){return `${top('4 / A NEW PATCH','The covered patch.','Both water and light are low. Plant support is already small. Find a repair and follow the recovery through more than one step.')}${panel()}${checks('Which explanation fits the repair?', [['both','Restore light and water. Plants improve first; food support can help consumers later.'],['water','Only water matters. Plants never need light.']],'Inspect both resource controls. Keep advancing and read the journal; changes use the previous step’s food support.')}<section id="complete" class="card" ${done.has(4)?'':'hidden'}><h3>You followed the connections.</h3><p>Resources supported plants. Plants supported herbivores. Herbivores supported a predator. Our model recovered according to its rules; a real meadow has many more needs and no guaranteed repair.</p><p>Next practice: draw a food path on paper. Change one resource and explain one possible effect and one thing our model leaves out.</p>${button('replay','Explore again',true)}</section>`;}
function next(p){return `<div class="next"><button data-go="${p-2}">← Previous</button><button data-go="${p}" class="primary">Next activity →</button></div>`;}
function advance(){const before=plantTotal(habitat),r=step(habitat);habitat=r.state;log=r.log;const after=plantTotal(habitat),direction=after>before?'up':after<before?'down':'same';observed=`Plant support: ${before} → ${after}. ${prediction==='skip'?'Prediction skipped.':`You predicted ${prediction}; the model went ${direction}. ${prediction===direction?'Your prediction matched this step.':'Compare the journal and try another prediction.'}`}`;refresh();}
function refresh(){const focused=document.activeElement?.id;render();if(focused&&$('#'+focused))$('#'+focused).focus();}
function render(){$('#main').innerHTML=[home,build,experiment,restore,final][page]();$$('nav button').forEach(b=>{if(+b.dataset.page===page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('#progress').textContent=`${done.size} / 4 activities explored`;bind();}
function bind(){const on=(id,f)=>{if($('#'+id))$('#'+id).onclick=f;};on('start',()=>go(1));on('step',()=>{stop();advance();});on('play',()=>{if(timer){stop();refresh();}else{timer=setInterval(advance,2500);refresh();}});on('reset',reset);on('replay',resetAll);for(const id of ['water','light'])if($('#'+id))$('#'+id).onchange=e=>{stop();habitat[id]=+e.target.value;refresh();};if($('#prediction'))$('#prediction').onchange=e=>{prediction=e.target.value;};if($('#scenario'))$('#scenario').onchange=e=>{key=e.target.value;reset();};$$('[data-organism]').forEach(b=>b.onclick=()=>{stop();habitat=toggle(habitat,b.dataset.organism);observed='Habitat choices changed. Advance a step to inspect their effect.';refresh();});$$('[data-go]').forEach(b=>b.onclick=()=>go(+b.dataset.go));on('check',()=>{stop();$('#play').textContent='Run slowly';const answer=$('input[name=answer]:checked')?.value;if(!answer){$('#feedback').textContent='Choose an idea first. You can open the help.';return;}const correct={1:'food',2:'plants',3:'grass',4:'both'}[page];if(answer!==correct){$('#feedback').textContent='Follow the food and resource links. Plants need light and water; consumers need appropriate food. Try again.';return;}if(habitat.tick<1||(page!==2&&!viable(habitat))){$('#feedback').textContent='Your idea follows the links. Now apply it: include all five species, give water and light at least 4, and step until all support scores reach at least 4. For the experiment, just inspect one step.';return;}done.add(page);$('#progress').textContent=`${done.size} / 4 activities explored`;$('#feedback').textContent='Your idea and observed model fit. This is a simplified explanation, not a promise about real habitats.';if(page===4)$('#complete').hidden=false;});}
function resetAll(){stop();done=new Set();go(0);}$$('nav button').forEach(b=>b.onclick=()=>go(+b.dataset.page));$('#reset-all').onclick=resetAll;$('.brand').onclick=e=>{e.preventDefault();go(0);};document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();if(page)render();}});render();
